### ISSUE TITLE
Provide reasonable requirements

### ISSUE THREAD

**Issue by jgieseler** [spearhead-he/VDA#4]
The `requirements.txt` should contain _reasonable_ requirements. That means it should include:
- the _minimal_ amount of packages needed, not all packages that are installed (e.g., [astropy-iers-data](https://pypi.org/project/astropy-iers-data/) should not be listed, as it should be installed and used directly by [astropy](https://pypi.org/project/astropy/)
- _reasonable_ version numbers that are not too restrictive (e.g., `astropy>=6.1.7` instead of `astropy==6.1.7`; only use `==` if it is really needed).

Otherwise, we will end up needing a specific environment for each and every of our tools; the aim is rather to have in the end one "spearhead" environment that can run at least all of our tools.

**Comment by liadlow** [comment]
Solved in aac6eca1027592d2b7ac2f012cab64bfa556d3a5
